#!/usr/bin/env python3

import requests
import json
import csv

# Load secrets
try:
    with open('secrets.json') as f:
        secrets = json.load(f)
except:
    secrets = {}

# Load config
try:
    with open('config.json') as f:
        config = json.load(f)
except:
    config = {}

# Inject config with secrets.
config['api_key'] = secrets.get('api_key')

# Main app
if __name__ == "__main__":
    page = 1
    movies = []
    params = {
            'api_key': config.get('api_key'),
            'primary_release_year': config.get('year'),
            'with_original_language': 'en',
            'without_genres': ','.join([str(x) for x in config.get('without_genres', [])]),
            'include_adult': 'false'
    }
 
    while True:
        params['page'] = page
        response = requests.get('https://api.themoviedb.org/3/discover/movie', params=params)
        results = json.loads(response.text).get('results')
        
        if len(results) > 0:
            movies = movies + results
            page += 1
        else:
            break

    with open(config.get("output_file"), 'w') as f:
        #headers = list(movies[0].keys())
        headers = ['release_date', 'overview', 'title', 'popularity']
        w = csv.DictWriter(f, extrasaction='ignore', fieldnames=headers)
        w.writeheader()
        w.writerows(movies)
